# 参考：https://github.com/Tiryoh/actions-mkdocs
name: Deploy

on: [pull_request]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          # 安装行内公式渲染的依赖(python-markdown-math)
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option
